apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: cs16-admin
  namespace: cs
data:
  users.ini: |
    "STEAM_0:1:978447" "" "abcdefghijklmnopqrstuz" "ce"
    "STEAM_0:1:64467321" "" "abcdefghijklmnopqrstuz" "ce"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs16-deployment
  labels:
    app: cs16
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs16
  template:
    metadata:
      labels:
        app: cs16
    spec:
      containers:
      - name: cs16
        image: mattiashem/cs16
        env:
        - name: MAXPLAYERS
          value: "32"
        - name: SERVER_NAME
          value: "game.robots.beer"
        - name: START_MONEY
          value: "800"
        - name: BUY_YIME
          value: "0.25"
        - name: FRIENDLY_FIRE
          value: "1"
        - name: SERVER_PASSWORD
          value: "matte"
        - name: RCON_PASSWORD
          value: "dess2ddd"
        ports:
          - containerPort: 27015
          - containerPort: 27015
            protocol: UDP
        volumeMounts:
        - name: config-volume
          mountPath: /opt/hlds/cstrike/addons/amxmodx/configs/users.ini
          subPath: users.ini
      nodeSelector:
        cpu: amd64
      volumes:
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: cs16-admin
---

kind: Service
apiVersion: v1
metadata:
  name: cs16-service-tcp
spec:
  type: NodePort
  selector:
    app: cs16
  ports:
  - protocol: TCP
    nodePort: 32216
    port: 27015
    targetPort: 27015


---

kind: Service
apiVersion: v1
metadata:
  name: cs16-service-udp
spec:
  type: NodePort
  selector:
    app: cs16
  ports:
  - protocol: UDP
    nodePort: 32215
    port: 27015
    targetPort: 27015
    
